In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

ModuleNotFoundError: No module named 'seaborn'

In [16]:
#create the DataFrame utilizing Pandas 
data = pd.read_csv('sales_data_raw.csv')

In [17]:
print("raw shape:", data.shape)

raw shape: (1030, 7)

In [18]:
data.head(5)

,sales_date,product_id,item_description,quantity,unit_price,customer_id,transaction_id
0,2023-02-28 07:09:32.972972973,PROD-0023,Unknown Product,4.0,366.69,CUST-00128,TXN-000032
1,2023-06-15 18:51:31.891891892,PROD-0048,Unknown Product,6.0,35.46,CUST-00050,TXN-000110
2,2023-05-05 23:26:50.810810812,PROD-0021,Unknown Product,1.0,482.59,CUST-00062,TXN-000137
3,2023-11-14 08:40:21.621621624,PROD-0024,Unknown Product,9.0,66.24,CUST-00113,TXN-000089
4,2023-10-24 14:13:20.000000000,PROD-0035,Unknown Product,9.0,215.53,CUST-00056,TXN-000919

In [19]:
data.tail(10)

,sales_date,product_id,item_description,quantity,unit_price,customer_id,transaction_id
1020,2023-05-26 17:53:52.432432432,PROD-0011,Unknown Product,7.0,227.26,CUST-00188,TXN-000309
1021,2023-07-20 09:36:34.594594596,PROD-0021,Unknown Product,9.0,186.51,CUST-00100,TXN-000662
1022,2023-01-06 02:25:35.135135135,PROD-0021,Unknown Product,9.0,253.93,CUST-00024,TXN-000131
1023,2023-04-15 22:29:11.351351352,PROD-0036,Unknown Product,1.0,422.93,CUST-00022,TXN-000664
1024,2023-05-31 20:19:27.567567568,PROD-0025,Unknown Product,7.0,367.14,CUST-00057,TXN-000872
1025,2023-07-24 09:48:06.486486488,PROD-0033,Unknown Product,8.0,266.46,CUST-00124,TXN-000088
1026,2023-10-06 00:14:24.864864864,PROD-0008,Smartphone,6.0,145.64,CUST-00092,TXN-000331
1027,2023-03-21 19:05:56.756756757,PROD-0021,Unknown Product,4.0,21.44,CUST-00157,TXN-000467
1028,2023-10-16 05:05:35.135135136,PROD-0025,Unknown Product,6.0,127.01,CUST-00182,TXN-000122
1029,2023-05-05 05:57:28.648648648,PROD-0001,Laptop Computer,2.0,388.10,CUST-00187,TXN-000861

In [9]:
# 2) Basic cleanup: trim strings + convert common "null" text to NaN
obj_cols = data.select_dtypes(include=["object", "string"]).columns
data[obj_cols] = data[obj_cols].apply(lambda s: s.astype("string").str.strip())
data.replace({"": np.nan, "na": np.nan, "n/a": np.nan, "null": np.nan, "none": np.nan}, inplace=True)

In [10]:
# 3) Drop fully-empty rows
data = data.dropna(how="all")

In [11]:
# 4) Remove duplicates
data = data.drop_duplicates()

In [12]:
print(data)

                         sales_date product_id item_description  quantity  \
0     2023-02-28 07:09:32.972972973  PROD-0023  Unknown Product       4.0
1     2023-06-15 18:51:31.891891892  PROD-0048  Unknown Product       6.0
2     2023-05-05 23:26:50.810810812  PROD-0021  Unknown Product       1.0
3     2023-11-14 08:40:21.621621624  PROD-0024  Unknown Product       9.0
4     2023-10-24 14:13:20.000000000  PROD-0035  Unknown Product       9.0
...                             ...        ...              ...       ...
1025  2023-07-24 09:48:06.486486488  PROD-0033  Unknown Product       8.0
1026  2023-10-06 00:14:24.864864864  PROD-0008       Smartphone       6.0
1027  2023-03-21 19:05:56.756756757  PROD-0021  Unknown Product       4.0
1028  2023-10-16 05:05:35.135135136  PROD-0025  Unknown Product       6.0
1029  2023-05-05 05:57:28.648648648  PROD-0001  Laptop Computer       2.0

      unit_price customer_id transaction_id
0         366.69  CUST-00128     TXN-000032
1          35.46  CUST-00050     TXN-000110
2         482.59  CUST-00062     TXN-000137
3          66.24  CUST-00113     TXN-000089
4         215.53  CUST-00056     TXN-000919
...          ...         ...            ...
1025      266.46  CUST-00124     TXN-000088
1026      145.64  CUST-00092     TXN-000331
1027       21.44  CUST-00157     TXN-000467
1028      127.01  CUST-00182     TXN-000122
1029      388.10  CUST-00187     TXN-000861

[1030 rows x 7 columns]

In [13]:
# 5) Handle nulls: fill numeric with median, text with mode
num_cols = data.select_dtypes(include=[np.number]).columns
data[num_cols] = data[num_cols].apply(lambda s: s.fillna(s.median()))

obj_cols = data.select_dtypes(include=["object", "string"]).columns
for c in obj_cols:
    if data[c].isna().any():
        mode = data[c].mode(dropna=True)
        data[c] = data[c].fillna(mode.iloc[0] if len(mode) else "")

In [14]:
data.head

<bound method NDFrame.head of                          sales_date product_id item_description  quantity  \
0     2023-02-28 07:09:32.972972973  PROD-0023  Unknown Product       4.0
1     2023-06-15 18:51:31.891891892  PROD-0048  Unknown Product       6.0
2     2023-05-05 23:26:50.810810812  PROD-0021  Unknown Product       1.0
3     2023-11-14 08:40:21.621621624  PROD-0024  Unknown Product       9.0
4     2023-10-24 14:13:20.000000000  PROD-0035  Unknown Product       9.0
...                             ...        ...              ...       ...
1025  2023-07-24 09:48:06.486486488  PROD-0033  Unknown Product       8.0
1026  2023-10-06 00:14:24.864864864  PROD-0008       Smartphone       6.0
1027  2023-03-21 19:05:56.756756757  PROD-0021  Unknown Product       4.0
1028  2023-10-16 05:05:35.135135136  PROD-0025  Unknown Product       6.0
1029  2023-05-05 05:57:28.648648648  PROD-0001  Laptop Computer       2.0

      unit_price customer_id transaction_id
0         366.69  CUST-00128     TXN-000032
1          35.46  CUST-00050     TXN-000110
2         482.59  CUST-00062     TXN-000137
3          66.24  CUST-00113     TXN-000089
4         215.53  CUST-00056     TXN-000919
...          ...         ...            ...
1025      266.46  CUST-00124     TXN-000088
1026      145.64  CUST-00092     TXN-000331
1027       21.44  CUST-00157     TXN-000467
1028      127.01  CUST-00182     TXN-000122
1029      388.10  CUST-00187     TXN-000861

[1030 rows x 7 columns]>